version: '3'

services: 
  mysql:
    image: mysql:8.0.33-debian
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: masterkey
      MYSQL_DATABASE: db_ativ04
      MYSQL_USER: root
      MYSQL_PASSWORD: masterkey
    ports:
      - 3306:3306